travis:
  secure:
    BINSTAR_TOKEN: Y41UJ2YNow7zeDtVVHQwSncG5v3atc08pGNR2AS+3X096LjtkRQtetxIr1ob7Y6Va4GJnpkKWk7TAluyvfGjxDooH387qAbO1jK9uTkDMG9Om3yURS7tH/CA1Q6m+MtvYyN5hcuXN/WeDc+Mt+cuu3hpP0NwSALve5VIuwbrfDqLOBSe+F4Amo26tjPhehAzsX9KYjbJbGoUAUHDcLk5SSHh1pgV+tZ0kiOtnQTsSydi/ZeYOz1YPl+chG4qvuvruLj3/SQZVpkFznAT3q/6MizTF+uJVN/dYajNj+nmPgaEI5Xnw+rjqSH+WTFPt1jgWS7Cw6Tf/pBeOQuVxv7H6e5GiYC/SCEAT5Mr0+fA+sJcMS4UEThDShjiQrwAnGNNNz7fQNl1mKMPlZSUGI9Px5wGK8XhVxm2qVEhcZmPfUzlNuseXXEN3+BJ7k7ptBfwxSG7VXeMxkvoPm9F/OFV9PdSz5vIon6zoncNxZT2RXWtXhTCuyhsYO2wL54b4uPt7JeUX1Sob65bdZkiMxFztNBUZaAjBPOcyMqomDtM3/9I8oogS3/v6lN3Ln5JCF00qyTrwKm9kI7TL0vSjLlJBcJfJqqfVbpeqEzp9zSJdSoNscjCZmnplb3gPcbvUfoVUgDZe7R/PEO5ZL1uDgGSTn/zx327f+6BKXWBCROvSJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
